services:
  chromium:
    image: torizon/chromium-imx8:4
    container_name: chromium
    volumes:
      - /tmp/1000-runtime-dir:/tmp/1000-runtime-dir
      - /var/run/dbus:/var/run/dbus
      - /dev/galcore:/dev/galcore
      - /dev/dri:/dev/dri
    environment:
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/tmp/1000-runtime-dir
    device_cgroup_rules:
      - 'c 199:* rmw'
      - 'c 226:* rmw'
    security_opt:
      - seccomp:unconfined
    shm_size: 256mb
    network_mode: host
    depends_on:
      - weston
    restart: always
    command: ["chromium", "--no-sandbox", "--kiosk", "http://127.0.0.1:8080"]

  weston:
    # image: torizon/weston-imx8:4
    image: torizon/weston-vivante:2
    environment:
      - ACCEPT_FSL_EULA=1
      - DISPLAY=:0
      - LAUNCH_WESTON=weston -Bdrm-backend.so -Swayland-0
    restart: always
    privileged: true
    # volumes:
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - /tmp/1000-runtime-dir:/tmp/1000-runtime-dir
      - /dev:/dev
      - /run:/run
      - /tmp:/tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    group_add:
      - "44"  # GID del grupo video, verifica con `getent group video`
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
      # ... for /dev/galcore device
      - 'c 199:* rmw'

  quickstart1-debug:
    container_name: quickstart1-debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/quickstart1-debug:${TAG}
    restart: always
    depends_on:
      - chromium
    volumes:
      - /tmp/wayland-0:/tmp/wayland-0
      - /var/rootdirs/media/my_sdcard:/mnt/microsd
    environment:
      - WAYLAND_DISPLAY=wayland-0
    network_mode: host
    devices:
      - /dev/dri/
      - /dev/spidev1.0
      - /dev/i2c-3
      - /dev/gpiochip2
      - /dev/gpiochip4
    group_add:
      - "${SPI_GID:-52}"
      - "${I2C_GID:-51}"
      - "${GPIO_GID:-49}"
    privileged: true

  quickstart1:
    container_name: quickstart1
    build:
      context: .
      dockerfile: Dockerfile
    image: quickstart1-debug:latest
    depends_on:
      - chromium
    volumes:
      - /tmp/wayland-0:/tmp/wayland-0
      - /var/rootdirs/media/my_sdcard:/mnt/microsd
    environment:
      - WAYLAND_DISPLAY=wayland-0
    network_mode: host
    devices:
      - /dev/dri/
      - /dev/spidev1.0
      - /dev/i2c-3
      - /dev/gpiochip2
      - /dev/gpiochip4
    group_add:
      - "${SPI_GID:-52}"
      - "${GPIO_GID:-51}"
      - "${SI2C_GID:-49}"
    privileged: true