services:
  quickstart1-debug:
    container_name: quickstart1-debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/quickstart1-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
      - ${DEBUG_PORT1}:${DEBUG_PORT1}
    devices:
      - /dev/spidev1.0
      - /dev/i2c-3
      - /dev/gpiochip2
      - /dev/gpiochip4
    group_add:
      - "${SPI_GID:-52}"
      - "${I2C_GID:-51}"
      - "${GPIO_GID:-49}"
    privileged: true

  quickstart1:
    container_name: quickstart1
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/quickstart1:${TAG}
    devices:
      - /dev/spidev1.0
      - /dev/i2c-3
      - /dev/gpiochip2
      - /dev/gpiochip4
    group_add:
      - "${SPI_GID:-52}"
      - "${GPIO_GID:-51}"
      - "${SI2C_GID:-49}"
    privileged: true