services:
  weston:
    image: torizon/weston-imx8:4
    environment:
      - ACCEPT_FSL_EULA=1
      - LAUNCH_APP=chromium --no-sandbox --kiosk http://localhost:8080
    network_mode: host
  quickstart1-debug:
    container_name: quickstart1-debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/quickstart1-debug:${TAG}
    volumes:
      - /tmp/wayland-0:/tmp/wayland-0
    environment:
      - WAYLAND_DISPLAY=wayland-0
    network_mode: host
    # ports:
    #   - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
    #   - ${DEBUG_PORT1}:${DEBUG_PORT1}
    #   - "8080:8080"
    devices:
      - /dev/dri/
      - /dev/spidev1.0
      - /dev/i2c-3
      - /dev/gpiochip2
      - /dev/gpiochip4
    group_add:
      - "${SPI_GID:-52}"
      - "${I2C_GID:-51}"
      - "${GPIO_GID:-49}"
    privileged: true

  quickstart1:
    container_name: quickstart1
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/quickstart1:${TAG}
    volumes:
      - /tmp/wayland-0:/tmp/wayland-0
    environment:
      - WAYLAND_DISPLAY=wayland-0
    network_mode: host
    # ports:
    #   - "8080:8080"
    devices:
      - /dev/spidev1.0
      - /dev/i2c-3
      - /dev/gpiochip2
      - /dev/gpiochip4
    group_add:
      - "${SPI_GID:-52}"
      - "${GPIO_GID:-51}"
      - "${SI2C_GID:-49}"
    privileged: true