version: "3.9"
services:
  chromium:
    image: torizon/chromium-imx8:4
    container_name: chromium
    volumes:
      - /tmp/1000-runtime-dir:/tmp/1000-runtime-dir
      - /var/run/dbus:/var/run/dbus
      - /dev/galcore:/dev/galcore
      - /dev/dri:/dev/dri
    environment:
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/tmp/1000-runtime-dir
    device_cgroup_rules:
      - 'c 199:* rmw'
      - 'c 226:* rmw'
    security_opt:
      - seccomp:unconfined
    shm_size: 256mb
    network_mode: host
    depends_on:
      - weston
    restart: always
    command: ["chromium", "--no-sandbox", "--kiosk", "http://127.0.0.1:8080", "--virtual-keyboard"]

  weston:
    image: torizon/weston-vivante:2
    environment:
      - ACCEPT_FSL_EULA=1
      - DISPLAY=:0
      - LAUNCH_WESTON=weston -Bdrm-backend.so -Swayland-0
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /tmp/1000-runtime-dir:/tmp/1000-runtime-dir
      - /dev:/dev
      - /run:/run
      - /tmp:/tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    group_add:
      - "44"
    cap_add:
      - CAP_SYS_TTY_CONFIG
    device_cgroup_rules:
      - 'c 4:0 rmw'
      - 'c 4:7 rmw'
      - 'c 13:* rmw'
      - 'c 226:* rmw'
      - 'c 199:* rmw'

  quickstart1-debug:
    container_name: quickstart1-debug
    # REMOVED build section - image already exists locally
    image: quickstart1-debug:arm64
    restart: always
    depends_on:
      - chromium
    volumes:
      - /tmp/wayland-0:/tmp/wayland-0
      - /var/rootdirs/media/my_sdcard:/mnt/microsd
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WAYLAND_DISPLAY=wayland-0
    network_mode: host
    devices:
      - /dev/dri/
      - /dev/spidev1.0
      - /dev/i2c-3
      - /dev/gpiochip2
      - /dev/gpiochip4
      - /dev/ttymxc1:/dev/verdin-uart2
    tty: true
    stdin_open: true
    group_add:
      - "52"
      - "51"
      - "49"
    privileged: true

  quickstart1:
    container_name: quickstart1
    # REMOVED build section - using same image as quickstart1-debug
    image: quickstart1-debug:arm64
    depends_on:
      - chromium
    volumes:
      - /tmp/wayland-0:/tmp/wayland-0
      - /var/rootdirs/media/my_sdcard:/mnt/microsd
      - /tmp:/tmp
    environment:
      - WAYLAND_DISPLAY=wayland-0
    network_mode: host
    devices:
      - /dev/dri/
      - /dev/spidev1.0
      - /dev/i2c-3
      - /dev/gpiochip2
      - /dev/gpiochip4
      - /dev/ttymxc1:/dev/verdin-uart2
    tty: true
    stdin_open: true
    group_add:
      - "52"
      - "51"
      - "49"
    privileged: true